### ISSUE TITLE
When width < 991px font is uppercase in carousel

### ISSUE THREAD

**Issue by CrazyLemon** [ubuntu-si/ubuntu.si#31]
So changing the width to 991px or smaller makes the carousel-text transform font to all uppercase. Not cool. 
So change needs to apply for smaller for every (?) rule lower than 991px.

**Comment by dz0ny** [comment]
Use media queries!!!

**Comment by CrazyLemon** [comment]
WE WILL!!!! WHAT ARE MEDIA QUERIES?!?
